name: Build macOS arm64 SDK (v5.8.1)

on:
  push:
    branches: [ "v5.8.1-custom" ]
  pull_request:
    branches: [ "v5.8.1-custom" ]
  workflow_dispatch:

jobs:
  build-macos-arm64:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
          brew install ninja yasm nasm autoconf automake libtool

    - name: Restore Cache
      uses: actions/cache/restore@v4
      with:
        path: |
          Library/TeamTalkLib/toolchain
          Build
        key: ${{ runner.os }}-macos-arm64-toolchain-${{ hashFiles('Library/TeamTalkLib/toolchain/**/CMakeLists.txt', 'Library/TeamTalkLib/toolchain/**/*.patch') }}-${{ github.run_id }}-${{ github.run_attempt }}
        restore-keys: |
          ${{ runner.os }}-macos-arm64-toolchain-${{ hashFiles('Library/TeamTalkLib/toolchain/**/CMakeLists.txt', 'Library/TeamTalkLib/toolchain/**/*.patch') }}-
          ${{ runner.os }}-macos-arm64-toolchain-

    - name: Build macOS arm64 SDK
      run: |
        cmake -B Build -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_TEAMTALK_CORE=ON \
          -DBUILD_TEAMTALK_STATIC=ON \
          -DCMAKE_OSX_ARCHITECTURES=arm64 \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 \
          -DTOOLCHAIN_BUILD_EXTERNALPROJECTS=ON \
          -DWEBRTC=ON \
          -DFEATURE_WEBRTC=ON \
          -DFEATURE_OPUSTOOLS=ON \
          -DFFMPEG=ON \
          -DOPUS=ON \
          -DSPEEX=ON \
          -DSPEEXDSP=ON \
          -DLIBVPX=ON \
          -DOGG=ON \
          -DDSHOW=ON \
          -DVIDCAP=ON \
          -DLAMEMP3=ON \
          -DBUILD_TEAMTALK5DLL=ON \
          -DBUILD_TEAMTALK5PRODLL=OFF \
          -DBUILD_TEAMTALK5LIB=OFF \
          -DBUILD_TEAMTALK5PROLIB=OFF \
          -DBUILD_TT5SRV=OFF \
          -DBUILD_TT5PROSRV=OFF \
          -DCATCH_UNITTEST=OFF
        
        cmake --build Build --target TeamTalk5DLL

    - name: Prepare architecture-specific artifact
      run: |
        cp Library/TeamTalk_DLL/libTeamTalk5.dylib Library/TeamTalk_DLL/libTeamTalk5-macos-arm64.dylib

    - name: Upload libTeamTalk5-macos-arm64.dylib Artifact
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: libTeamTalk5-macos-arm64
        path: Library/TeamTalk_DLL/libTeamTalk5-macos-arm64.dylib

    - name: Save Cache
      uses: actions/cache/save@v4
      if: always()
      with:
        path: |
          Library/TeamTalkLib/toolchain
          Build
        key: ${{ runner.os }}-macos-arm64-toolchain-${{ hashFiles('Library/TeamTalkLib/toolchain/**/CMakeLists.txt', 'Library/TeamTalkLib/toolchain/**/*.patch') }}-${{ github.run_id }}-${{ github.run_attempt }}
